---
services:
  kms:
    image: ${DOCKER_IMAGE_NAME}
    container_name: cosmian-kms
    environment:
      COSMIAN_KMS_CONF: /etc/cosmian/kms.toml
    volumes:
      - ../../pkg/kms.toml:/etc/cosmian/kms.toml:ro
    ports:
      - 9998:9998
