[package]
name = "cosmian_pkcs11_module"
version.workspace = true
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords = ["pkcs11", "cryptoki", "kms", "cosmian"]
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Cross-platform PKCS#11 module written in rust, originally forked from Google/native_pkcs11"

[lints]
workspace = true

[lib]
doctest = false

[features]
non-fips = []

[dependencies]
const-oid = "0.9.6"
hex = { workspace = true, features = ["std"] }
log = { workspace = true, default-features = false }
once_cell = "1.21.3"
openssl = { workspace = true }
p256 = { version = "0.13.2", default-features = false, features = [
  "arithmetic",
  "pkcs8",
  "std",
] }
pkcs1 = "0.7.5"
pkcs11-sys = { workspace = true }
rand = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
cosmian_logger = { workspace = true }
tracing = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
cosmian_logger = { workspace = true }
serial_test = { version = "3.2.0", default-features = true }
