[package]
name = "smartcardhsm_pkcs11_loader"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Smart card HSM PKCS#11 loader"

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
cosmian_kms_base_hsm = { path = "../base_hsm", version = "5.14.0" }

[dev-dependencies]
libloading = { workspace = true }
pkcs11-sys = { workspace = true }

[features]
# Enable this feature to run smartcardhsm tests (they require a Smart card HSM)
smartcardhsm = []
